# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - py.test --cov=planetary_test_data tests/
  - flake8 planetary_test_data
  - flake8 tests

after_success:
  - coveralls
